'use strict';

export const REQUEST_SIGNUP = 'REQUEST_SIGNUP';
export const RECEIVE_SIGNUP = 'RECEIVE_SIGNUP';
export const ERROR_SIGNUP = 'ERROR_SIGNUP';

export const FETCH_SPOT_LIST = 'FETCH_SPOT_LIST';
export const RECEIVE_SPOT_LIST = 'RECEIVE_SPOT_LIST';

export const FETCH_LOCATION = 'FETCH_LOCATION';
export const RECEIVE_LOCATION = 'RECEIVE_LOCATION';
