'use strict';

export const REQUEST_SIGNUP = 'REQUEST_SIGNUP';
export const RECEIVE_SIGNUP = 'RECEIVE_SIGNUP';

export const FETCH_REDDIT_LIST = 'FETCH_ARTICLE_LIST';
export const RECEIVE_REDDIT_LIST = 'RECEIVE_ARTICLE_LIST';
