'use strict';

export const HTTPSTATE = ["awaiting", "requesting"]
export const REQUEST_HTTP = "REQUEST_HTTP"
export const RECEIVE_HTTP = "RECEIVE_HTTP"

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';

export const REQUEST_SIGNUP = 'REQUEST_SIGNUP';
export const RECEIVE_SIGNUP = 'RECEIVE_SIGNUP';
export const ERROR_SIGNUP = 'ERROR_SIGNUP';

//spots
export const REQUEST_CREATE_SPOT = 'REQUEST_CREATE_SPOT';
export const CREATE_SPOT = 'CREATE_SPOT';
export const RECEIVE_CREATE_SPOT = 'RECEIVE_CREATE_SPOT';

export const REQUEST_UPDATE_SPOT_COVER = 'REQUEST_UPDATE_SPOT_COVER';
export const UPDATE_SPOT_COVER = 'UPDATE_SPOT_COVER';
export const RECEIVE_UPDATE_SPOT_COVER = 'RECEIVE_UPDATE_SPOT_COVER';

export const FETCH_SPOT_LIST = 'FETCH_SPOT_LIST';
export const RECEIVE_SPOT_LIST = 'RECEIVE_SPOT_LIST';
//spots

export const FETCH_LOCATION = 'FETCH_LOCATION';
export const RECEIVE_LOCATION = 'RECEIVE_LOCATION';
